### ISSUE TITLE
ERROR: pull access denied for digite/kairon-script-runner

### ISSUE THREAD

**Issue by escit** [digiteinfotech/kairon#1053]
ERROR: pull access denied for digite/kairon-script-runner, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by udit-pandey** [comment]
Hi, can you check now?

**Comment by escit** [comment]
Thank you! The issue seems to be resolved now. I am no longer encountering the 'pull access denied' error. I appreciate your assistance!
