### ISSUE TITLE
Please configure the bot endpoint for deployment!

### ISSUE THREAD

**Issue by sreenathmurali** [digiteinfotech/kairon#185]
Getting "Please configure the bot endpoint for deployment!" while trying to deploy bot .How to solve this?
Where can i get the documentation for all the GUI options!

**Comment by sfahad1414** [comment]
Sreenath, you need to configure IP of your rasa bot server, in Setup > Administration > Bot Configuration
![imageedit_2_6838349656](https://user-images.githubusercontent.com/10163662/114667647-56c07d00-9d1d-11eb-91b9-5f12ff4fa1cb.jpg)

**Comment by sreenathmurali** [comment]
Where can i get the documentation for all the GUI options?

**Comment by sfahad1414** [comment]
@sreenathmurali, we are onto it will share the short videos soon
