### ISSUE TITLE
Api action 

### ISSUE THREAD

**Issue by masoudMZB** [digiteinfotech/kairon#505]
Hello all
how can I create an API action? I don't see any doc or any example for it

I get this error : 

> The fields "{'headers'}" do not exist on the document "HttpActionConfig"

I have this simple get request `https://61e13d1463f8fc0017618ac5.mockapi.io/test/akbar` 
and the response will be : 

> {
    "key_test": "value_test"
}

I have one Rule which I want to use this api action. So which fields Should I fill.
in api action there are  : **Action name** |  **request_type** | **Headers** | **Body** | **Response**
How should I fill these parts

**Comment by udit-pandey** [comment]
Hi @masoudMZB,
Apologies that you had to face this issue. It would be great if you can share steps to recreate this issue.
From your requirements, I am sharing a screenshot of an API action i created.
![image](https://user-images.githubusercontent.com/18224381/149510465-ff955ce3-4223-4d4d-a435-6d095f7251af.png)

We expect a placeholder in the response field to fit your api response into. Users can either get complete response with ${RESPONSE} placeholder or a custom placeholder based on the api response.

**Comment by masoudMZB** [comment]
thanks for your answer this was the exact answer. I'll close this issue
